services:
  dev_frontend:
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_DOCKER_DEV=true
    develop:
      watch:
        - action: sync
          path: .